[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "innate-stable"
version = "0.3.0"
readme = { file = "README.rst", content-type = "text/x-rst" }
requires-python = ">=3.12"
license = {text = "GPL-3.0-or-later"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
               "Programming Language :: Python :: 3.12"]
authors = [{name = "Vital Fernández", email = "vgf@stsci.edu"}]
description = "Interpolator and Neural Network Architecture for TEnsors"
dependencies = ["numpy>=2.0,<3",
                "h5py>=3.11",
                "h5netcdf>=1.7"]

[tool.pytest.ini_options]
pythonpath = ["src"]
mpl-baseline-path = 'tests/baseline'
mpl-results-path = 'tests/outputs'
mpl-results-always = false
addopts = "--cov-report term --cov-report xml"