[metadata]
version = '0.1.8'

[parameter_labels]

# Data-sets
param = 'label'

# Interpolation
interp.'rgi' = 'regular grid interpolation'
interp.'near' = 'nearest-neighbour'
interp.'idw' = 'inverse distance weighting'
interp.'rdb' = 'radial basis function'

# Regression
reg.'eqn' = 'equation'
reg.'nn' = 'neural networks'
reg.'lgbm' = 'light gradient boosting maching'
reg.'svgp' = 'Staochastic Variational Guassian Process'

[colors] #Default theme
default.bg = '#FFFFFF'
default.fg = '#000000'
default.cont_band = '#8c564b'
default.line_band = '#b5bd61'
default.color_cycle = ['#279e68', '#d62728', '#aa40fc', '#8c564b',  '#e377c2', '#7f7f7f',
                       '#b5bd61', '#17becf', '#1f77b4', '#ff7f0e']

default.single_width = '1'
default.comp_width = '0.75'
default.err_width = '2'
default.cont_width = '0.5'
default.spectrum_width = '0.75'

#Dark theme
dark.bg = "#2B2B2B"
dark.fg = "#CCCCCC"
dark.cont_band = '#e7298a'
dark.line_band = '#8fff9f'
dark.color_cycle = ['#66c2a5', '#fc8d62', '#e68ac3', '#a6d854',  '#ffd92f', '#e5c494',
                       '#8dcbe2', '#e7298a', '#332288', '#88ccee']

dark.single_width = '1'
dark.comp_width = '0.75'
dark.err_width = '2'
dark.cont_width = '0.5'
dark.spectrum_width = '0.75'

[matplotlib]
default."figure.dpi" = 200
default."figure.figsize" = [4.85, 3]
default."axes.titlesize" = 9
default."axes.labelsize" = 9
default."legend.fontsize" = 7
default."xtick.labelsize" = 8
default."ytick.labelsize" = 8
default."font.size" = 5

high_res."figure.dpi" = 300
high_res."figure.figsize" = [11, 6]
high_res."axes.titlesize" = 14
high_res."axes.labelsize" = 14
high_res."legend.fontsize" = 12
high_res."xtick.labelsize" = 12
high_res."ytick.labelsize" = 12

dark."figure.facecolor" = "#2B2B2B"
dark."axes.facecolor" = "#2B2B2B"
dark."axes.edgecolor" = "#CCCCCC"
dark."axes.labelcolor" = "#CCCCCC"
dark."xtick.labelcolor" = "#CCCCCC"
dark."ytick.labelcolor" = "#CCCCCC"
dark.'xtick.color'= "#CCCCCC"
dark.'ytick.color'= "#CCCCCC"
dark."text.color" = "#CCCCCC"
dark."legend.edgecolor" = "inherit"
dark."legend.facecolor" = "inherit"

# Plots
bands."axes.labelsize" = 8
bands."legend.fontsize" = 5
